import './globals.css'
import { Inter } from 'next/font/google'

import Menu from "./component/menu"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'static login',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu />
        {children}
      </body>
    </html>
  )
}
